#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const writeMode = process.argv.includes("--write");
const checkMode = process.argv.includes("--check");

if (!writeMode && !checkMode) {
  console.error("Usage: node scripts/sync-harness.mjs --write|--check");
  process.exit(2);
}

const generatedHeader = "<!-- Generated by npm run sync:harness. Do not edit by hand. -->\n\n";

function normalize(value) {
  return value.replace(/\r\n/g, "\n");
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function writeIfNeeded(relativePath, content, diffs) {
  const absolute = path.join(root, relativePath);
  const current = fs.existsSync(absolute) ? normalize(fs.readFileSync(absolute, "utf8")) : null;
  const next = normalize(content);
  if (checkMode) {
    if (current !== next) diffs.push(relativePath);
    return;
  }
  ensureDir(path.dirname(absolute));
  fs.writeFileSync(absolute, next, "utf8");
}

function listSkillDirs(relativeBase) {
  const base = path.join(root, relativeBase);
  if (!fs.existsSync(base)) return [];
  return fs
    .readdirSync(base, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && fs.existsSync(path.join(base, entry.name, "SKILL.md")))
    .map((entry) => ({ name: entry.name, source: path.join(relativeBase, entry.name, "SKILL.md") }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

function listAgentFiles() {
  const base = path.join(root, ".codex/agents");
  if (!fs.existsSync(base)) return [];
  return fs
    .readdirSync(base, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".toml"))
    .map((entry) => `.codex/agents/${entry.name}`)
    .sort();
}

function agentMarkdown(relativePath) {
  const body = read(relativePath);
  const base = path.basename(relativePath, ".toml").replaceAll("_", "-");
  return `${generatedHeader}# ${base}\n\nSource: \`${relativePath}\`.\n\n\`\`\`toml\n${body.trim()}\n\`\`\`\n`;
}

function sync() {
  const diffs = [];
  const skills = [
    ...listSkillDirs("plugins/v-pl-codex/skills"),
    ...listSkillDirs(".agents/skills"),
  ];

  const readme = `${generatedHeader}# Claude Skill Mirror\n\nThese skills are generated from canonical V_PL Codex sources.\nEdit \`plugins/v-pl-codex/skills/**\` or \`.agents/skills/**\`, then run \`npm run sync:harness\`.\n`;
  writeIfNeeded(".claude/skills/README.md", readme, diffs);

  for (const skill of skills) {
    writeIfNeeded(`.claude/skills/${skill.name}/SKILL.md`, read(skill.source), diffs);
  }

  for (const agent of listAgentFiles()) {
    const targetName = path.basename(agent, ".toml").replaceAll("_", "-");
    writeIfNeeded(`.claude/agents/${targetName}.md`, agentMarkdown(agent), diffs);
  }

  const settings = {
    hooks: {
      SessionStart: [
        {
          matcher: "startup|resume",
          hooks: [
            {
              type: "command",
              command: "node .codex/hooks/session-start.js",
              timeout: 5,
              statusMessage: "Loading V_PL context",
            },
          ],
        },
      ],
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: "command",
              command: "node .codex/hooks/user-prompt-nudge.js",
              timeout: 5,
            },
          ],
        },
      ],
    },
  };
  writeIfNeeded(".claude/settings.json", `${JSON.stringify(settings, null, 2)}\n`, diffs);

  if (checkMode && diffs.length) {
    console.error("Claude harness mirror is out of sync:");
    for (const diff of diffs) console.error(`- ${diff}`);
    process.exit(1);
  }

  console.log(checkMode ? "Claude harness mirror in sync." : "Claude harness mirror written.");
}

sync();

